### ISSUE TITLE
A negative match on one test should not stop the rest

### ISSUE THREAD

**Issue by lilyball** [zkat/supports-hyperlinks#1]
Right now, if one of the env vars tested exists but doesn’t pass the requisite test, it doesn’t check the rest. This can cause false negatives.

For example, if I launch `kitty` from Terminal.app. `TERM_PROGRAM` is set to `Apple_Terminal` (Kitty doesn’t set this var), but `TERM` is set to `xterm-kitty`. This crate will return `false` though as it checks `TERM_PROGRAM` first and doesn’t even look at `TERM` if it’s set.

More generally, the issue is this crate tests vars that are not guaranteed to be set by the terminal emulator, and therefore might have been inherited. This can cause false positives too, such as if a supporting terminal launches one that doesn’t support it but doesn’t set `TERM_PROGRAM`, but that’s less of an issue as hyperlinks degrade gracefully.

**Comment by zkat** [comment]
Fixed :)
