### ISSUE TITLE
Support env var to force hyperlinks on (or off)

### ISSUE THREAD

**Issue by lilyball** [zkat/supports-hyperlinks#2]
There should be a way for me, as a user, to explicitly request hyperlinks (or turn them off). Declaring an env var for this is the obvious choice.

Requesting would be for if my terminal supports it but the code hasn’t been updated for it, or if the env var normally used to detect it has been modified (e.g. if I use Kitty and ssh to another machine, I have to reset my TERM as xterm-kitty is not in standard terminfo databases, but doing so means my terminal can’t be detected as Kitty anymore).

Turning it off is for false positives (e.g. my terminal doesn’t support it but has inherited an env var that is used to detect support).

**Comment by lilyball** [comment]
For reference, I just found an NPM package called `supports-hyperlinks` [which defines](https://github.com/jamestalmage/supports-hyperlinks/blob/66834a8a4ccc07f9af6364778fcaa0666b61eccb/index.js#L27-L29) the `FORCE_HYPERLINK` var. The logic here appears to be "if `FORCE_HYPERLINK` exists, a value matching `/^\s*0+(?!\d)/` means disable hyperlinks, anything else enables them", though I'm not sure they really meant for `FORCE_HYPERLINK=0xF` to mean disable hyperlinks, I suspect they actually just wanted to trim whitespace.

**Comment by zkat** [comment]
Fixed :)
